import { Product, Review } from './types';

// The exact image paths generated by the image model
import auraImage from './assets/images/tshirt_aura_1782311890246.jpg';
import urduImage from './assets/images/tshirt_urdu_1782311908449.jpg';
import cyberImage from './assets/images/tshirt_cyber_1782311923890.jpg';
import acidImage from './assets/images/tshirt_acid_1782311941926.jpg';

export const PRODUCTS: Product[] = [
  {
    id: 'aura-tee',
    name: 'AURA Oversized Tee',
    tagline: 'Vibe check! High-definition glowing print with dropping shoulders.',
    price: 1499,
    originalPrice: 2999,
    badge: '🔥 viral on tiktok',
    image: auraImage,
    gsm: 240,
    fit: 'Oversized Drop-Shoulder',
    print: 'Dual-Layer Premium Puff Print',
    fabric: '100% Cotton French Terry',
    colors: ['Jet Black'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    description: 'Elevate your daily streetwear game with our best-selling AURA T-Shirt. Designed with a structured heavyweight 240 GSM organic cotton fabric, it gives the perfect slouchy streetwear silhouette. Features a bold neon blue and magenta visual graphic printed using advanced dual-layer puff ink that stands out under any light.'
  },
  {
    id: 'urdu-sukun-tee',
    name: 'SUKUN Urdu Script Tee',
    tagline: 'Our cultural roots meet modern urban streetwear aesthetics.',
    price: 1499,
    originalPrice: 2999,
    badge: '✨ premium selection',
    image: urduImage,
    gsm: 240,
    fit: 'Oversized Slouchy Fit',
    print: 'High-Density Screen Print',
    fabric: '100% Premium Cotton',
    colors: ['Charcoal Grey'],
    sizes: ['M', 'L', 'XL'],
    description: 'Sukun (سُکون) meaning "peace". A fusion of heritage and contemporary Gen-Z style. Features sleek, custom Urdu calligraphy in a bright neon yellow and cyan gradient, capturing the essence of cultural pride blended with urban streetwear. Heavy, breathable fabric built for absolute comfort.'
  },
  {
    id: 'cyber-hyd-tee',
    name: 'CYBER-HYD Graphic Tee',
    tagline: 'Futuristic synthwave visuals inspired by neon cyber aesthetics.',
    price: 1599,
    originalPrice: 3199,
    badge: '⚡ hot seller',
    image: cyberImage,
    gsm: 240,
    fit: 'Oversized Fit',
    print: 'Vibrant Premium Digital Print',
    fabric: '100% Premium Combed Cotton',
    colors: ['Snow White'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    description: 'The CYBER-HYD limited edition tee brings electric, glowing digital artwork on a crisp, heavy snow-white base. The neon pink, electric blue, and golden cyberpunk graphic is soft to the touch but exceptionally vivid. A certified conversation starter, guaranteed to grab attention in your TikTok transitions.'
  },
  {
    id: 'vibecheck-acid-tee',
    name: 'VIBE CHECK Acid Wash Tee',
    tagline: 'Premium vintage washed-out texture for a laid-back street style.',
    price: 1399,
    originalPrice: 2799,
    badge: '🎨 limited drop',
    image: acidImage,
    gsm: 220,
    fit: 'Classic Drop-Shoulder',
    print: 'Minimalist Puff Print',
    fabric: '100% Cotton Vintage Acid Wash',
    colors: ['Vintage Purple Wash'],
    sizes: ['M', 'L', 'XL'],
    description: 'Crafted with custom dye and enzyme washing processes, each single VIBE CHECK t-shirt has a completely unique washed-out pattern. Features a subtle, minimal puff logo on the chest, making it the perfect piece to layer under a jacket or style standalone.'
  }
];

export const REVIEWS: Review[] = [
  {
    id: 'rev-1',
    author: 'Zainab Lodhi',
    city: 'Karachi',
    rating: 5,
    text: 'Aura oversized tee is outstanding! The fabric is super heavy and thick (exact 240 GSM as promised) and puff print quality is amazing. Highly recommended for streetwear fans in Pakistan! 🔥 Will buy more.',
    date: '2026-06-20',
    verified: true,
    productName: 'AURA Oversized Tee'
  },
  {
    id: 'rev-2',
    author: 'Hamza Mughal',
    city: 'Lahore',
    rating: 5,
    text: 'TikTok pe ad dekha aur buy kar liya. Deliver bohot tez hua (only 2 days in Lahore). "Sukun" text look and gradient colours match visual details perfectly. Pure soft cotton quality, perfect for summer nights!',
    date: '2026-06-22',
    verified: true,
    productName: 'SUKUN Urdu Script Tee'
  },
  {
    id: 'rev-3',
    author: 'Daniyal Ahmed',
    city: 'Islamabad',
    rating: 5,
    text: 'Cyber Hyd white tee feels so premium. Oversized fit is exactly what I wanted. Usually, sizes online are tight, but HYD Shop fitting is 10/10. Cash on Delivery was seamless. Ordering more for my brothers.',
    date: '2026-06-23',
    verified: true,
    productName: 'CYBER-HYD Graphic Tee'
  },
  {
    id: 'rev-4',
    author: 'Ayesha Khattak',
    city: 'Peshawar',
    rating: 4,
    text: 'Fabric feel is premium. Very comfortable and fits like a dream. Acid wash finish is extremely cool. Packaging was very neat, came with free HYD shop stickers. ⚡ 5-stars for Pakistani local brand!',
    date: '2026-06-18',
    verified: true,
    productName: 'VIBE CHECK Acid Wash Tee'
  },
  {
    id: 'rev-5',
    author: 'Saad Malik',
    city: 'Faisalabad',
    rating: 5,
    text: 'Best oversizes in Pakistan! Cash on Delivery delivery boy called before coming. Print still solid after 2 washes, color fade nahi hua. Recommended to my TikTok followers.',
    date: '2026-06-24',
    verified: true,
    productName: 'AURA Oversized Tee'
  }
];

export const PAKISTANI_CITIES = [
  'Karachi',
  'Lahore',
  'Islamabad',
  'Faisalabad',
  'Rawalpindi',
  'Multan',
  'Peshawar',
  'Hyderabad',
  'Gujranwala',
  'Quetta',
  'Sialkot',
  'Bahawalpur',
  'Sargodha',
  'Sukkur',
  'Larkana',
  'Sheikhupura',
  'Rahim Yar Khan',
  'Jhang',
  'Dera Ghazi Khan',
  'Gujrat',
  'Sahiwal',
  'Wah Cantt',
  'Mardan',
  'Kasur',
  'Okara',
  'Mingora',
  'Nawabshah',
  'Chiniot',
  'Kotri',
  'Kamoke',
  'Hafizabad',
  'Sadiqabad',
  'Mirpur Khas',
  'Khanewal',
  'Muzaffargarh',
  'Kohat',
  'Muzaffarabad',
  'Abbottabad'
];
